export const USER_CONSENT_TYPE = {
  AGE_CONFIRMATION_OVER_14: 'AGE_CONFIRMATION_OVER_14',
  TERMS_OF_SERVICE: 'TERMS_OF_SERVICE',
  PERSONAL_INFORMATION_COLLECTION_AND_USE:
    'PERSONAL_INFORMATION_COLLECTION_AND_USE',
  MARKETING_INFORMATION_RECEIPT: 'MARKETING_INFORMATION_RECEIPT',
} as const;

export type UserConsentType =
  (typeof USER_CONSENT_TYPE)[keyof typeof USER_CONSENT_TYPE];
