name: testAndDeploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node_version: '20.x'
      - name: Install npm packages
        run: npm ci
      - name: test build
        run: npm run build

  dev-deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up SSh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_DEV_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up known hosts
        run: |
          echo "${{ secrets.SSH_DEV_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH and deploy
        run: |
          ssh ${{ secrets.SSH_DEV_USERNAME }}@${{ secrets.SSH_DEV_PUBLIC_IP }} "
          cd newdok-backend
          git pull origin dev
          npm install
          npx prisma generate
          npm run build
          sudo pm2 kill
          npm run deploy:dev
          exit
          "
